"""Initial migrate

Revision ID: 2b73ea8084dc
Revises: 
Create Date: 2023-12-07 09:48:37.376449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b73ea8084dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairing', schema=None) as batch_op:
        batch_op.drop_constraint('chooser_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairing', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['chosen_id'], ['id'])

    # ### end Alembic commands ###
